Export Vault struct and begin adding doc strings
pangeacyber/pangea-go pull request #65
Opened 2023-03-29 21:25 UTC by r3dcrosse

While working on adding vault doc strings, I noticed the `Vault` struct in `vault/service.go` was not getting exported since it starts with a lowercase `v`. 

This changes makes it an uppercase `V` to export it, and begins adding doc strings.

Please let me know if there is something that should change, or if we should not export this struct. We do export the struct for each service, so I thought it was odd that we were not doing it for vault.

2023-03-31 11:59 UTC, pangea-andrest commented
As I talked with @dbenders some time ago, the idea is to keep the implementation private, so no export it (that's why 'v' lowercase). It's true that's not what is done in other services but we thought about start doing 'the right' way since then. I think we can't change it right know due to It could be a breaking change but if we are releasing SDK v2.0 we can do all in the same way

2023-03-31 12:46 UTC, pangea-andrest requested changes

2023-03-31 12:46 UTC, pangea-andrest commented on pangea-sdk/service/vault/service.go
> +	cli := &Vault{
It won't be a breaking change due to we still return a `Client` but IMO we should keep it private. We can talk it with @ggallien13 @govind-salinas-pangea also maybe

2023-03-31 12:46 UTC, pangea-andrest commented on pangea-sdk/service/vault/api.go
> +//			RotationState:     pangea.StringValue("deactivated"),
This should be `ItemVersionState`, I think I should fix it in SDK v2. (Just comment, nothing you need to do here now)

2023-04-10 17:40 UTC, pangea-andrest commented
@r3dcrosse any update here?

2023-04-10 18:35 UTC, r3dcrosse commented
@pangea-andrest Revisiting this today. 

I'm taking a look at where the best place to move the doc strings is. 

The problem I'm running into is doc strings are nonexistent on the private implementation. 

I'm thinking the way to fix this is to move the doc strings to `service.go` since `Client` is public:

```
type Client interface {
    // put doc strings here....

}

```

Also open to other suggestions for where doc strings should live going forward.

2023-04-10 20:52 UTC, pangea-andrest commented
Oh, I didn't know about that problem, but totally agree about putting them into Client interface, developers will have all the methods and docs right there and in a cleaner and organized way IMO, avoiding all the implementation in the middle

2023-04-28 23:41 UTC, r3dcrosse commented
Closing this PR in favor of https://github.com/pangeacyber/pangea-go/pull/74

2023-04-28 23:41 UTC, closed without merging